# Generated by Django 3.2.5 on 2021-07-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='additional_info',
            field=models.TextField(default='-'),
        ),
    ]
