# Generated by Django 3.2.5 on 2021-07-07 14:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_analysis_indicator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodtest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
